### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by jadbox** [aidansteele/aws_sdk.nim#2]
Firstly: you're doing god(s) work by making an aws sdk for Nim.. thanks!

It would be great to have test cases to show its quality and test coverage (even if it's low to start).

**Comment by aidansteele** [comment]
Thanks for the kind words 😄 though I must confess I am relatively new to Nim and still have much to learn. 

Which brings me to my next point: do you have any recommendations/examples of The Right Way to do unit testing and code coverage reports for Nim projects? I currently have ad-hoc tests at the end of source files that run when compiled with `-d:testing`, e.g. [signaturev4.nim](https://github.com/aidansteele/aws_sdk.nim/blob/master/aws_sdk/signaturev4.nim#L125) and [signaturev2.nim](https://github.com/aidansteele/aws_sdk.nim/blob/master/aws_sdk/signaturev2.nim#L47) but I am very keen to expand and standardise them.

**Comment by aidansteele** [comment]
I think we can consider this done now thanks to @yglukhov's work in #7 and #9.
